<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.3.0.8</Version>
    <Description>Display what is playing in your server bar, and play/pause/skip.</Description>
    <PackageProjectUrl>https://github.com/wompscode/NowPlaying</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NPSMLib" Version="0.9.14" />
    <PackageReference Include="Tmds.DBus.Generator" Version="0.95.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.95.0" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="dbus-xml/org.mpris.MediaPlayer2.Player.xml" Namespace="Mpris.DBus" DBusGeneratorMode="Proxy" />
  </ItemGroup>
</Project>
